apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    run: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080