apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" . }}
{{ include "mychart.app" . | indent 4 }}  
data:
  myvalue: "Hello World"
  myfruit: {{ .Values.fruit | upper | quote }}
  optionalvalue: {{ .Values.optionalValue | default "not set"  | upper | repeat 3 | quote }}
{{ include "mychart.app" . | indent 2 }}
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" }}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}  