apiVersion: v1
kind: Service
metadata:
  name: blue-green
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  # this service sends requests to blue-green that matches any pod with same set of labels.    
  # loose coupling
  selector:
    app: blue-green
