apiVersion: v1
kind: Service
metadata:
  name: blue-green
spec:
  # ClusterIP a type of IP assigned to the Pod. Only accessible within cluster.
  # Cluster Scoped IP    
  #type: ClusterIP

  # NodePort expose a random port IP on the worker node.
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: blue-green
